[package]
name = "flash-arb"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "flash_arb"

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
