[package]
name = "price-fetcher"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.18.17"
solana-sdk = "1.18.17"
anyhow = "1.0"
borsh = "0.10"
log = "0.4"
thiserror = "1.0"
orca_whirlpools_client = "0.4.3"
anchor-lang = "0.29.0"
